[build]
  command = "npm ci --prefer-offline --no-audit --no-fund && npm run build:netlify"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"
  VITE_APP_ENV = "production"
  DISABLE_SENTRY = "true"
  # Disable smart detection for environment variable names that trigger false positives
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
